### PR TITLE
Wew thats a lot of changes

### PR DESCRIPTION
**Pull request by AzyIsCool**
Don't try to merge yet, going to do some more checks and maybe some more stuff

### CODE REVIEW

**Comment by AzyIsCool** [comment]
You can now merge, here's the list of things that have been done:

* Updated UI + Icons
* Language can now be changed
* White theme (for the brave souls out there)
* Under the hood changes
* Updates can now be installed without prompt
* You can allow it to make the taskbar icon not disappear when minimized
* Shows icon providers in credits
* progress bar to show how far it is into installing an update
* update failed page is now a thing, allowing people to retry the update
* if no discord client is open it will wait for one to open and only show the mainpage when all discord processes are running
* MainWindow now has a MinWith so if user snaps window the window will be the min size it needs to be
* Fixed window not showing when there is MultiRPC process running and the user tries to open another one
* Fixed taskbar icon not disappearing when the window is minimized

**Comment by AzyIsCool** [comment]
Wew it isn't working on Win7 let's see why...

**Comment by AzyIsCool** [comment]
Ok now it works on Win7 (PresentationFramework.Aero2 was to blame)

**Comment by ChineseMarc** [comment]
That's a lot of damage

**Pull request merged**
